"""crear tabla personas

Revision ID: 1c8b16c62277
Revises: 
Create Date: 2026-06-18 14:34:01.105072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c8b16c62277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimientos')
    op.drop_table('personas')
    op.drop_table('medicamentos')
    op.drop_table('roles')
    op.drop_table('atenciones_medicas')
    op.drop_table('vacunaciones')
    op.drop_table('secciones_procedimientos')
    op.drop_table('enfermedades')
    op.drop_table('prescripciones')
    op.drop_table('procedimiento_realizado')
    op.drop_table('analisis')
    op.drop_table('tipos_atenciones')
    op.drop_table('campanas_salud')
    op.drop_table('estados_atenciones')
    op.drop_table('diagnosticos')
    op.drop_table('parametros')
    op.drop_table('participantes')
    op.drop_table('tipos_parametros')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment=None,
               existing_comment='Identificador del usuario',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='Nombre de acceso del usaurio',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='Contraseña del usuario',
               existing_nullable=False)
        batch_op.alter_column('rol_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment=None,
               existing_comment='Identificador del rol del usuario',
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=False,
               comment=None,
               existing_comment='Estado de acceso del usuario')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_constraint(batch_op.f('usuarios_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuarios_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('persona_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la persona asociada al usuario'))
        batch_op.create_foreign_key(batch_op.f('usuarios_ibfk_2'), 'personas', ['persona_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('usuarios_ibfk_1'), 'roles', ['rol_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('estado',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='Estado de acceso del usuario')
        batch_op.alter_column('rol_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='Identificador del rol del usuario',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               comment='Contraseña del usuario',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               comment='Nombre de acceso del usaurio',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='Identificador del usuario',
               existing_nullable=False,
               autoincrement=True)

    op.create_table('tipos_parametros',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del tipo de parámetro de análisis'),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False, comment='Nombre del parámetro de análisis'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('participantes',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del participante de la campaña'),
    sa.Column('campana_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la campaña de salud'),
    sa.Column('atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la atención médica brindada'),
    sa.Column('observacion', mysql.TEXT(), nullable=True, comment='Observaciones sobre la participación'),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones_medicas.id'], name=op.f('participantes_ibfk_2')),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas_salud.id'], name=op.f('participantes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('parametros',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del parámetro de análisis'),
    sa.Column('tipo_parametro_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del tipo de parámetro'),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False, comment='Nombre del parámetro'),
    sa.Column('valor_referencia_min', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Valor de referencia normal mínimo'),
    sa.Column('valor_referencia_max', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Valor de referencia normal máximo'),
    sa.Column('unidad_medida', mysql.VARCHAR(length=255), nullable=True, comment='Unidad de medida del parámetro'),
    sa.Column('observacion', mysql.TEXT(), nullable=True, comment='Observaciones sobre el parámetro'),
    sa.ForeignKeyConstraint(['tipo_parametro_id'], ['tipos_parametros.id'], name=op.f('parametros_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('diagnosticos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='Identificador de tabla de diagnosticos'),
    sa.Column('enfermedad_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='Identificador de enfermedad'),
    sa.Column('descripcion', mysql.TEXT(), nullable=True, comment='Descripción del diagnóstico'),
    sa.Column('fecha', sa.DATE(), nullable=False, comment='Fecha del diagnóstico'),
    sa.Column('atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la atención médico'),
    sa.Column('responsable_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='Identificador del usuario responsable'),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones_medicas.id'], name=op.f('diagnosticos_ibfk_2')),
    sa.ForeignKeyConstraint(['enfermedad_id'], ['enfermedades.id'], name=op.f('diagnosticos_ibfk_1')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('diagnosticos_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('estados_atenciones',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del estado de atención médica'),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False, comment='Nombre del estado'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('campanas_salud',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la campaña de salud'),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=True, comment='Nombre de la campaña'),
    sa.Column('objetivo', mysql.TEXT(), nullable=True, comment='Objetivo de la campaña'),
    sa.Column('desde', sa.DATE(), nullable=False, comment='Fecha de inicio'),
    sa.Column('hasta', sa.DATE(), nullable=False, comment='Fecha de cierre'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('tipos_atenciones',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del tipo de atención médica'),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False, comment='Nombre del tipo de atención médica'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('analisis',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la tabla análisis'),
    sa.Column('atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la atención médica'),
    sa.Column('parametro_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del parámetro analizado'),
    sa.Column('valor_resultado', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Valor del resultado obtenido'),
    sa.Column('observacion', mysql.TEXT(), nullable=True, comment='Observaciones'),
    sa.Column('fechahora_muestra', mysql.DATETIME(), nullable=False, comment='Fecha y hora de la muestra'),
    sa.Column('fechahora_analisis', mysql.DATETIME(), nullable=False, comment='Fecha y hora en que se realiza el analisis'),
    sa.Column('responsable_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del usuario resposanble'),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones_medicas.id'], name=op.f('analisis_ibfk_1')),
    sa.ForeignKeyConstraint(['parametro_id'], ['parametros.id'], name=op.f('analisis_ibfk_2')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('analisis_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('procedimiento_realizado',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del procedimiento realizado'),
    sa.Column('procedimiento_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del procedimiento médico'),
    sa.Column('atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la atención médica'),
    sa.Column('fecha', sa.DATE(), nullable=False, comment='Fecha de realización del procedimiento'),
    sa.Column('observacion', mysql.TEXT(), nullable=True, comment='Obsvervaciones sobre el procedimiento'),
    sa.Column('responsable_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del usuario responsable'),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones_medicas.id'], name=op.f('procedimiento_realizado_ibfk_2')),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos.id'], name=op.f('procedimiento_realizado_ibfk_1')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('procedimiento_realizado_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('prescripciones',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la prescripción médica'),
    sa.Column('medicamento_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del medicamento prescrito'),
    sa.Column('atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='\u206fIdentificador de la atención médica'),
    sa.Column('dosis', mysql.VARCHAR(length=255), nullable=False, comment='Descripción de la dosis a administrar'),
    sa.Column('fecha', sa.DATE(), nullable=False, comment='Fecha de la prescripción'),
    sa.Column('cantidad', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Cantidad prescrita del medicamento'),
    sa.Column('responsable_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='Identificador del usuario responsable'),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones_medicas.id'], name=op.f('prescripciones_ibfk_2')),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], name=op.f('prescripciones_ibfk_1')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('prescripciones_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('enfermedades',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la enfermedad'),
    sa.Column('nombre', mysql.VARCHAR(length=512), nullable=False, comment='Nombre de la enfermedad'),
    sa.Column('codigo_cie10', mysql.VARCHAR(length=7), nullable=True, comment='Código CIE-10 (Clasificación Internacional de Enfermedades, 10ª revisión)'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('secciones_procedimientos',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la sección del procedimiento médico'),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False, comment='Nombre del procedimiento médico'),
    sa.Column('codigo', mysql.VARCHAR(length=4), nullable=True, comment='Código de la sección médica'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('vacunaciones',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la vacuna aplicada'),
    sa.Column('atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la atención médica'),
    sa.Column('medicamento_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del medicamento administrado'),
    sa.Column('cantidad', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='Cantidad del medicamente adminstrado'),
    sa.Column('fecha', sa.DATE(), nullable=False, comment='Fecha de la vacunación'),
    sa.Column('numero_dosis', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True, comment='Número de la dosis administrada'),
    sa.Column('responsable_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del usuario responsable'),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones_medicas.id'], name=op.f('vacunaciones_ibfk_1')),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], name=op.f('vacunaciones_ibfk_2')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('vacunaciones_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('atenciones_medicas',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la atención médica'),
    sa.Column('fecha_hora', mysql.DATETIME(), nullable=False, comment='Fecha y hora de la atención médica'),
    sa.Column('estado_atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del estado de la atención'),
    sa.Column('paciente_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del paciente'),
    sa.Column('responsable_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='Identificador del usuario responsable'),
    sa.Column('tipo_atencion_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador del tipo de atención médica'),
    sa.ForeignKeyConstraint(['estado_atencion_id'], ['estados_atenciones.id'], name=op.f('atenciones_medicas_ibfk_1')),
    sa.ForeignKeyConstraint(['paciente_id'], ['personas.id'], name=op.f('atenciones_medicas_ibfk_2')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('atenciones_medicas_ibfk_3')),
    sa.ForeignKeyConstraint(['tipo_atencion_id'], ['tipos_atenciones.id'], name=op.f('atenciones_medicas_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del rol de usuario'),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False, comment='Nombre del rol'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('medicamentos',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del medicamente'),
    sa.Column('codigo', mysql.VARCHAR(length=255), nullable=False, comment='Código interno del medicamento'),
    sa.Column('denominacion', mysql.VARCHAR(length=255), nullable=True, comment='Denominación del medicamento'),
    sa.Column('especificaciones_tecnicas', mysql.TEXT(), nullable=True, comment='Especificaciones ténicas del medicamento'),
    sa.Column('unidad_medida', mysql.VARCHAR(length=10), nullable=True, comment='Unidad de medida del medicamento'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('personas',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador de la tabla'),
    sa.Column('numero_documento', mysql.VARCHAR(length=15), nullable=True, comment='Número de documento de identidad'),
    sa.Column('primer_apellido', mysql.VARCHAR(length=100), nullable=True, comment='Primer apellido de la persona'),
    sa.Column('segundo_apellido', mysql.VARCHAR(length=100), nullable=True, comment='Segundo apellido de la persona'),
    sa.Column('nombres', mysql.VARCHAR(length=100), nullable=True, comment='Nombres de la persona'),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True, comment='Fecha de nacimiento de la persona'),
    sa.Column('sexo', mysql.VARCHAR(length=1), nullable=True, comment='Sexo de la persona'),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True, comment='Dirección de la persona'),
    sa.Column('telefono', mysql.VARCHAR(length=100), nullable=True, comment='Número telefónico de la persona'),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=True, comment='Correo electrónico de la persona'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('procedimientos',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='Identificador del procedimiento médico'),
    sa.Column('codigo_cpms', mysql.VARCHAR(length=8), nullable=False, comment='Código del Catálogo de Procedimientos Médicos y Sanitarios (CPMS)'),
    sa.Column('nombre', mysql.VARCHAR(length=512), nullable=False, comment='Nombre del procedimiento'),
    sa.Column('seccion_procedimiento_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='Identificador de la sección del procedimiento médico'),
    sa.ForeignKeyConstraint(['seccion_procedimiento_id'], ['secciones_procedimientos.id'], name=op.f('procedimientos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
